name: user_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  authentication_client:
    path: ../authentication_client/authentication_client
  equatable: ^2.0.7
  rxdart: ^0.28.0
  

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0

