name: firebase_authentication_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  authentication_client:
    path: ../authentication_client
  firebase_auth: ^6.0.2
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  token_storage:
    path: ../token_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
